### ISSUE TITLE
An error occurred while calling o74.save.

### ISSUE THREAD

**Issue by ronniemo** [cordon-thiago/airflow-spark#11]
Hey @cordon-thiago,

running the postgres example produces the following:
 
File "/usr/local/spark/app/read-postgres.py", line 72, in <module>
df_result.coalesce(1).write.format("csv").mode("overwrite").save("/usr/local/spark/resources/data/output_postgres", header=True)
py4j.protocol.Py4JJavaError: An error occurred while calling o74.save.

**Comment by cordon-thiago** [comment]
Hi @ronniemo can you send me the whole log, please? Tks
