### ISSUE TITLE
ERROR: The image for the service you're trying to recreate has been removed

### ISSUE THREAD

**Issue by EloneSampaio** [cordon-thiago/airflow-spark#19]
**when execute docker-compose up -d get this error:**

**Pulling airflow-webserver (docker-airflow-spark:1.10.7_3.1.2)...
ERROR: The image for the service you're trying to recreate has been removed. If you continue, volume data could be lost. Consider backing up your data before continuing.**

**Comment by Danstnou** [comment]
> **when execute docker-compose up -d get this error:**
> 
> **Pulling airflow-webserver (docker-airflow-spark:1.10.7_3.1.2)... ERROR: The image for the service you're trying to recreate has been removed. If you continue, volume data could be lost. Consider backing up your data before continuing.**

you first need to build an image.
before "docker-compose up -d" run:
docker build --rm --force-rm -t docker-airflow-spark: 1.10.7_3.1.2.
The image will be created and found.

**Comment by cordon-thiago** [comment]
> **when execute docker-compose up -d get this error:**
> 
> **Pulling airflow-webserver (docker-airflow-spark:1.10.7_3.1.2)... ERROR: The image for the service you're trying to recreate has been removed. If you continue, volume data could be lost. Consider backing up your data before continuing.**

Hi @EloneSampaio after building the image was your problem solved?

**Comment by EloneSampaio** [comment]
yes, thanks for helping.
