### ISSUE TITLE
spark_job SparkSubmitOperator failed

### ISSUE THREAD

**Issue by ronniemo** [cordon-thiago/airflow-spark#2]
Hey and thanks for the nice project,

when I follow the steps from the README it ends up with an Error: 

` [2020-11-02` 09:33:37,559] {{taskinstance.py:1088}} ERROR - Cannot execute: ['spark-submit', '--master', 'spark://spark:7077', '--conf', 'spark.master=spark://spark:7077', '--name', 'Spark Hello World', '--verbose', '--queue', 'root.default', '/usr/local/spark/app/hello-world.py', '/usr/local/spark/resources/data/airflow.cfg']. Error code is: 1.
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 955, in _run_raw_task
    result = task_copy.execute(context=context)
  File "/usr/local/lib/python3.6/site-packages/airflow/contrib/operators/spark_submit_operator.py", line 181, in execute
    self._hook.submit(self._application)
  File "/usr/local/lib/python3.6/site-packages/airflow/contrib/hooks/spark_submit_hook.py", line 362, in submit
    spark_submit_cmd, returncode
airflow.exceptions.AirflowException: Cannot execute: ['spark-submit', '--master', 'spark://spark:7077', '--conf', 'spark.master=spark://spark:7077', '--name', 'Spark Hello World', '--verbose', '--queue', 'root.default', '/usr/local/spark/app/hello-world.py', '/usr/local/spark/resources/data/airflow.cfg']. Error code is: 1.
[2020-11-02 09:33:37,560] {{taskinstance.py:1117}} INFO - All retries failed; marking task as FAILED
[2020-11-02 09:33:40,835] {{logging_mixin.py:112}} INFO - [2020-11-02 09:33:40,834] {{local_task_job.py:103}} INFO - Task exited with return code 1`

Seems 
[log.txt](https://github.com/cordon-thiago/airflow-spark/files/5474104/log.txt)

**Comment by ronniemo** [comment]
Just to make sure everything is set up correctly: running the Jupyter notebook example doesn't work without adding: 

`from pyspark import SparkContext ` and `sc = SparkContext()`

**Comment by ronniemo** [comment]
When i add spark-scripts to `/jovyan/work/hello-world.py` and run `docker exec -it docker_jupyter-spark_1 spark-submit --master local /home/jovyan/work/spark-scripts/hello-world.py` it works but how can i make it run by airflow?

**Comment by ronniemo** [comment]
After updating to spark 3.0.1. its running from Airflow too.

**Comment by cordon-thiago** [comment]
> Hey and thanks for the nice project,
> 
> when I follow the steps from the README it ends up with an Error:
> 
> ` [2020-11-02` 09:33:37,559] {{taskinstance.py:1088}} ERROR - Cannot execute: ['spark-submit', '--master', 'spark://spark:7077', '--conf', 'spark.master=spark://spark:7077', '--name', 'Spark Hello World', '--verbose', '--queue', 'root.default', '/usr/local/spark/app/hello-world.py', '/usr/local/spark/resources/data/airflow.cfg']. Error code is: 1.
> Traceback (most recent call last):
> File "/usr/local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 955, in _run_raw_task
> result = task_copy.execute(context=context)
> File "/usr/local/lib/python3.6/site-packages/airflow/contrib/operators/spark_submit_operator.py", line 181, in execute
> self._hook.submit(self._application)
> File "/usr/local/lib/python3.6/site-packages/airflow/contrib/hooks/spark_submit_hook.py", line 362, in submit
> spark_submit_cmd, returncode
> airflow.exceptions.AirflowException: Cannot execute: ['spark-submit', '--master', 'spark://spark:7077', '--conf', 'spark.master=spark://spark:7077', '--name', 'Spark Hello World', '--verbose', '--queue', 'root.default', '/usr/local/spark/app/hello-world.py', '/usr/local/spark/resources/data/airflow.cfg']. Error code is: 1.
> [2020-11-02 09:33:37,560] {{taskinstance.py:1117}} INFO - All retries failed; marking task as FAILED
> [2020-11-02 09:33:40,835] {{logging_mixin.py:112}} INFO - [2020-11-02 09:33:40,834] {{local_task_job.py:103}} INFO - Task exited with return code 1`
> 
> Seems
> [log.txt](https://github.com/cordon-thiago/airflow-spark/files/5474104/log.txt)

Hi @ronniemo! Please, check if the Airflow connection `spark_default` is configured as explained in the Readme  https://github.com/cordon-thiago/airflow-spark#how-to-run-a-dag-to-test.

**Comment by cordon-thiago** [comment]
> After updating to spark 3.0.1. its running from Airflow too.

Hi @ronniemo. It worked with me and I'm still using Spark 2.4.5. As I suggested in the above comment, review your Airflow connection with Spark. It should work with this spark version.

**Comment by cordon-thiago** [comment]
> Just to make sure everything is set up correctly: running the Jupyter notebook example doesn't work without adding:
> 
> `from pyspark import SparkContext ` and `sc = SparkContext()`

Fixed here: https://github.com/cordon-thiago/airflow-spark/pull/4
