### ISSUE TITLE
 ModuleNotFoundError: No module named 'wtforms.compat'

### ISSUE THREAD

**Issue by ssabalain** [cordon-thiago/airflow-spark#22]
Hi!

I'm keep getting this error while doing docker-compose up:

`airflow-webserver_1  | ModuleNotFoundError: No module named 'wtforms.compat'`

I've followed all the steps from the .md file. Any clue on what could be happening?

btw I'm running it on WSL2.

**Comment by lfelicianolucas** [comment]
Adding wtforms==2.3.3 to the requirements.txt (airflow-spark/docker/docker-airflow/requirements.txt) file before executing the docker build command solved the problem for me.

https://stackoverflow.com/questions/69879246/no-module-named-wtforms-compat

**Comment by ssabalain** [comment]
Thank you very much @lfelicianolucas ! Indeed, that solved the issue. Maybe could be a quick fix for you to add, @cordon-thiago , just to have a key-in-hand solution!
