### ISSUE TITLE
new version of pip

### ISSUE THREAD

**Issue by ronniemo** [cordon-thiago/airflow-spark#3]
Hey, 

when building the docker image there appears this ERROR message. 

```bash 

ERROR: After October 2020 you may experience errors when installing or updating packages. This is because pip will change the way that it resolves dependency conflicts.

We recommend you use --use-feature=2020-resolver to test your packages with the new resolver before it becomes the default.

marshmallow-sqlalchemy 0.24.0 requires marshmallow>=3.0.0, but you'll have marshmallow 2.21.0 which is incompatible.
```

**Comment by cordon-thiago** [comment]
There is a new version of pip and to ensure compatibility, the flag `--use-feature=2020-resolver` was added as mentioned here https://discuss.python.org/t/announcement-pip-20-2-release/4863.
Fixed in this merge https://github.com/cordon-thiago/airflow-spark/pull/4
