### ISSUE TITLE
ERROR: failed to solve: process "/bin/sh -c set -ex ... && pip freeze" did not complete successfully: exit code: 100

### ISSUE THREAD

**Issue by d-T-ReX-b** [cordon-thiago/airflow-spark#39]
Hi all! On Windows 10 in any console (cmd, git bash) after

docker build --rm -t docker-airflow2:latest .

i got the error:

`ERROR: failed to solve: process "/bin/sh -c set -ex     && buildDeps='         freetds-dev         libkrb5-dev         libsasl2-dev         libssl-dev         libffi-dev         libpq-dev         git     '     && apt-get update -yqq     && apt-get upgrade -yqq     && apt-get install -yqq --no-install-recommends         $buildDeps         freetds-bin         build-essential         default-libmysqlclient-dev         apt-utils         curl         rsync         netcat         locales         iputils-ping         telnet     && locale-gen     && update-locale LANG=en_US.UTF-8 LC_ALL=en_US.UTF-8     && useradd -ms /bin/bash -d ${AIRFLOW_HOME} airflow     && pip install -U pip setuptools wheel     && pip install pytz     && pip install pyOpenSSL     && pip install ndg-httpsclient     && pip install pyasn1     && pip install -r requirements.txt     && pip install --use-feature=2020-resolver apache-airflow[crypto,celery,postgres,hive,jdbc,mysql,ssh${AIRFLOW_DEPS:+,}${AIRFLOW_DEPS}]==${AIRFLOW_VERSION}     && pip install 'redis>=2.10.5,<3'     && if [ -n \"${PYTHON_DEPS}\" ]; then pip install ${PYTHON_DEPS}; fi     && apt-get purge --auto-remove -yqq $buildDeps     && apt-get autoremove -yqq --purge     && apt-get clean     && rm -rf         /var/lib/apt/lists/*         /tmp/*         /var/tmp/*         /usr/share/man         /usr/share/doc         /usr/share/doc-base     && python --version     && pip freeze" did not complete successfully: exit code: 100`

Docker seems to be workable.

What's wrong?

**Comment by 20cent16** [comment]
Same issue on Ubuntu 22.04. 
This code is just too old to work in 2024, some url are different now. The best thing to do is to start from zero by following airflow official documentation.

**Comment by d-T-ReX-b** [comment]
> Same issue on Ubuntu 22.04. This code is just too old to work in 2024, some url are different now. The best thing to do is to start from zero by following airflow official documentation.

Yes, i've already found workable image. Thanks.
