### ISSUE TITLE
Why pulling images when using *build*?

### ISSUE THREAD

**Issue by ronniemo** [cordon-thiago/airflow-spark#5]
Usually, images are pulled by running `docker build`, so why pulling the three images again?

**Comment by suryakolachana** [comment]
Hello,

Can we use docker build -t command to create all the images?

**Comment by cordon-thiago** [comment]
> Usually, images are pulled by running `docker build`, so why pulling the three images again?

In recent commits of this repo, the images are pulled once. You just want to build the airflow image and the others are pulled when you run the docker-compose.

**Comment by cordon-thiago** [comment]
> Hello,
> 
> Can we use docker build -t command to create all the images?

I don't think so because they are in different folders.
